/* llms.txt, regenerated by build-pages.js so the page list in it cannot drift
   from the pages that exist.
 *
 * The ledger names AI-answer citation as an acquisition channel, and the
 * competitor already ships one. What it has to be is accurate: an llms.txt
 * that promises pages the site does not have is worse than none. */

const title = (html) => (html.match(/<h1>([\s\S]*?)<\/h1>/) || [, ''])[1]
  .replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
const desc = (html) => (html.match(/<meta name="description" content="([^"]*)"/) || [, ''])[1]
  .replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#39;|&rsquo;/g, "'").trim();

function llmsTxt(pages) {
  const byUrl = new Map(pages.map((p) => [p.url, p]));
  const line = (url) => {
    const p = byUrl.get(url);
    return p ? `- ${url}: ${title(p.html)} — ${desc(p.html)}` : null;
  };

  const hub = line('/tools/');
  const calculators = [
    '/tools/peptide-reconstitution-calculator/',
    '/tools/insulin-syringe-units-calculator/',
    '/tools/trt-dose-calculator/',
    '/tools/free-testosterone-calculator/',
    '/tools/half-life-calculator/',
    '/tools/syringe-builder/',
    '/tools/stack-checker/'
  ].map(line).filter(Boolean);

  const recon = pages
    .filter((p) => /-reconstitution-calculator\/$/.test(p.url) &&
                   p.url !== '/tools/peptide-reconstitution-calculator/')
    .map((p) => `- ${p.url}: ${title(p.html)}`);

  const halfLife = pages
    .filter((p) => /^\/tools\/half-life\/[^/]+\/$/.test(p.url))
    .map((p) => `- ${p.url}: ${title(p.html)}`);

  const markerHub = line('/markers/');
  const markers = pages
    .filter((p) => /^\/markers\/[^/]+\/$/.test(p.url))
    .map((p) => `- ${p.url}: ${title(p.html)} — ${desc(p.html)}`);

  /* Blend pages carry their community nicknames, because that is what someone
     asking an assistant about one will have typed. */
  const blends = pages
    .filter((p) => /-blend-calculator\/$/.test(p.url))
    .map((p) => `- ${p.url}: ${title(p.html)} — ${desc(p.html)}`);

  return `# TherapyLog

> TherapyLog is a web-based TRT (testosterone replacement therapy) and peptide
> tracker for adults. It logs doses, models estimated serum levels from published
> half-lives, plans multi-compound syringe draws with compatibility rules, and
> tracks bloodwork against the reference range printed on the user's own lab
> report. Health data stays on the user's device. Free tier, no account required.

Site: https://therapylog.app/
Publisher: TherapyLog LLC, Floresville, Texas, USA
Contact: hello@therapylog.app

Generated by scripts/build-pages.js — the page list below is the page list that
exists, not a roadmap.

Disambiguation: "Therapylog" is also the name of an unrelated school-therapy
documentation product at therapylog.com. This is a different product. This one is
at therapylog.app and is a hormone-therapy and peptide tracker.

## Author and editorial policy

All reference content is written by Joel Gonzales, founder of TherapyLog. He is
not a clinician, and the site states that on every page. No clinical reviewer is
claimed. Claims cite primary literature or guideline documents; evidence is
labelled in three tiers (established clinical use, off-label or community
practice, animal-only or theoretical); the reference range printed on a user's
own lab report takes precedence over any generic range shown; optimal bands are
labelled non-diagnostic; every side-effect discussion ends with taking the result
to the prescribing clinician. The site sells software only, lists no vendor on
any reference page, and takes no referral fee from any clinic, pharmacy or
laboratory.

- /about/: Author, editorial policy, corrections process, what the site earns
  from, and what the tools do and do not do.

## Core pages

- /: What TherapyLog is, who it is for, and pricing.
- /app: The tracker itself. Runs in the browser, installs to the home screen.
- /guide: Full user guide — every tab, control and workflow.
- /pro: The paid tier. Pro is $9.99/month or $99.99/year for managed AI; a
  bring-your-own-API-key plan is offered alongside it at a lower price. Paid
  features are the AI lab scanner and the AI assistant; the calculators, the
  compound reference and bloodwork logging are not behind the AI gate.
- /download: How to install it on iPhone and Android. There is no app-store
  listing; it is a web app installed to the home screen.
- /support: FAQ and support contact.
- /partnership: Affiliate and partner program.
- /directory/ and /providers/: Provider directory and provider signup.
- /privacy, /health-data-privacy, /terms: Legal policies.

## Free calculators

Every calculator runs the app's own function source, lifted from the app when the
page is built and compared against it in continuous integration, so a page and
the app cannot disagree about a number. All are free and need no account.

${hub}

${calculators.join('\n')}

### Reconstitution, pre-filled per compound

Each carries a milligram-to-units table computed for a stated vial and diluent
volume, the modelled half-life, and the storage rule.

${recon.join('\n')}

### Pre-mixed multi-peptide blends

A blend vial holds several peptides dissolved in the same water, so one draw
takes all of them in the ratio the vial was compounded at. These pages compute
what a single draw delivers of each component and compare it against what the
literature and community practice describe for that compound on its own; the two
rarely match, because the ratio is fixed by whoever filled the vial. Ratios are
not standardised, so each page takes the numbers from the reader's own label.
The BPC-157 and TB-500 vial is widely known by the community nickname the
"Wolverine blend" or "Wolverine stack"; GLOW is GHK-Cu with BPC-157 and TB-500;
KLOW is GLOW with KPV added.

${blends.join('\n')}

### Half-life and steady state, per compound

Each carries the single-dose and repeated-dose curves pre-rendered from the app's
own pkCurve function, the accumulation ratio, the time to steady state, the
peak-to-trough ratio, the monitoring panel, and the interaction rules naming that
compound. Estimated half-lives are labelled as estimates on every page they
appear on.

${halfLife.join('\n')}

## Lab marker reference (/markers/)

Marker pages are written with the assay method named wherever it changes the
interpretation — sensitive (LC/MS-MS) versus standard immunoassay estradiol,
direct versus calculated versus equilibrium-dialysis free testosterone, and so
on. Each will carry the accepted units and their conversions, the generic
reference range labelled as generic, the non-diagnostic optimal band where one
exists, and authored explanation with primary sources. The hub at /markers/ lists
what is live; the fifteen markers being written are estradiol (sensitive versus
standard), total testosterone (immunoassay versus LC/MS-MS), free versus total
testosterone, SHBG, hematocrit on testosterone therapy, prolactin, LH and FSH,
IGF-1, HbA1c and fasting glucose, ApoB versus LDL, lipoprotein(a), ferritin and
the iron panel, vitamin D, the thyroid panel, and DHT.

## Lab marker reference

Written with the assay method named wherever it changes the interpretation —
sensitive (LC/MS-MS) versus standard immunoassay estradiol, direct versus
calculated versus equilibrium-dialysis free testosterone, and so on. Each page
carries the accepted units and their conversion factors, the assay variants the
app tracks, the generic reference range labelled as generic, the non-diagnostic
optimal band where one exists, the sex and age bands generated from the app's own
range function, a unit converter running the app's own conversion code, and cited
primary sources. The reference interval printed on the reader's own report always
takes precedence over any generic range shown.

${markerHub}

${markers.join('\n')}

## Disclaimer

TherapyLog is an informational tracking tool and is not a substitute for
professional medical advice, diagnosis, or treatment. It does not diagnose, treat,
prescribe or monitor anyone. Calculators do the arithmetic entered into them and
nothing else; vial strength and diluent volume must be confirmed on the user's own
label. Serum-level curves are modelled estimates from published half-lives, not
measurements, and where the underlying half-life is itself an estimate the page
says so. It is for adults; the app requires an 18-or-older attestation.
Always consult a qualified healthcare provider before starting, changing, or
stopping any medical protocol.
`;
}

module.exports = { llmsTxt, title, desc };
